apiVersion : v1
kind : Pod
metadata : 
  name : config-pod
  labels : 
    app : my-config-pod

spec : 
  containers : 
    - name : config-pod
      image : vishymails/tomcatimage:1.0
      volumeMounts:
        - name : config-vol
          mountPath : /etc/config
          readOnly : true
          
  volumes:
    - name : config-vol
      configMap :
        name : myconfig

