apiVersion : apps/v1
kind : DaemonSet
metadata :
  name : fluent-ds

spec :
  template :
    metadata :
      labels :
        name : fluentd
    spec : 
      containers :
        - image : gcr.io/google-containers/fluentd-elasticsearch:1.20
          name : fluentd

  selector :
    matchLabels :
      name : fluentd

