apiVersion : v1
kind : Pod
metadata : 
  name : init-container-demo
  labels : 
    app : tomcat
    tier : dev
spec : 
  containers : 
    - name : tomcat-container
      image : vishymails/tomcatimage:1.0
