apiVersion : v1
kind : Pod
metadata : 
  name : tomacat-pod
  labels : 
    app : tomcat
    tier : dev
spec : 
  containers : 
    - name : tomcat-container
      image : vishymails/tomcatimage:1.0
      volumeMounts :
        - name : test-vol
          mountPath : /my-volume


  volumes :
    - name : test-vol
      hostPath :
        path : /test-vol
