apiVersion : v1
kind : Pod
metadata : 
  name : secret-pod
  labels : 
    app : my-secret-pod

spec : 
  containers : 
    - name : secret-pod
      image : vishymails/tomcatimage:1.0
      volumeMounts:
        - name : sec-vol
          mountPath : /etc/secret
          readOnly : true
          
  volumes:
    - name : sec-vol
      secret :
        secretName : my-secret

